Style/IndentationWidth:
    Width: 4

Style/StringLiterals:
    EnforcedStyle: double_quotes

Style/GlobalVars:
    AllowedVariables:
        - $db

Style/WordArray:
    Enabled: false

Metrics/LineLength:
    Max: 100

AllCops:
    Exclude:
        - "bin/satapi"
