---
language: ruby
rvm:
  - jruby
env:
  - JRUBY_OPTS="--2.0"
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

install:
  - bundle install --without production development
  - rake deps

script:
  - bundle exec rubocop
  - shopt -s globstar && ruby -wc **/*.rb
