---
language: ruby
# Travis consults .ruby-version
jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8
env:
    global:
        - RACK_ENV=test
        - JRUBY_OPTS=--2.0

install:
    - bundle install --without production development
    - rake javalibs

script:
    - bundle exec rubocop --format fuubar
    - shopt -s globstar && ruby -wc **/*.rb
    - rake spec
